# Application name configuration.
# This sets the name of the application as it appears in logs and other places.
spring.application.name=clik

# Active profile configuration.
# This determines which set of configuration files are used.
# The default profile is 'dev', but this can be overridden by setting the CLIK_PROFILE environment variable.
spring.profiles.active=${CLIK_PROFILE:dev}

# Corrected Properties for Spring Boot 2.x and 3.x
logging.file.name=/Users/legion/work/projects/clik/logs/clik.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=5