# Application name configuration.
# This sets the name of the application as it appears in logs and other places.
spring.application.name=clik

# Active profile configuration.
# This determines which set of configuration files are used.
# The default profile is 'dev', but this can be overridden by setting the CLIK_PROFILE environment variable.
spring.profiles.active=${CLIK_PROFILE:dev}

# Corrected Properties for Spring Boot 2.x and 3.x
logging.file.name=/Users/legion/work/projects/clik/logs/clik.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=5

# Optimization for high throughput 
# Increase maximum worker threads (Default: 200)
# server.tomcat.threads.max=800

# # Increase the waiting room queue before Tomcat rejects connections (Default: 100)
# server.tomcat.accept-count=1500

# # Increase maximum connections Tomcat will keep alive (Default: 8192)
# server.tomcat.max-connections=10000

# # Increase database connections
# spring.datasource.hikari.maximum-pool-size=100